### PR TITLE
Changed my PFP to a GIF

### PR DESCRIPTION
**Pull request by IAmJSD**
Because the doge GIF isn't the same without the doge moving :)

### CODE REVIEW

**Comment by foxt** [comment]
Don't think you should accept it. Could be very distracting.

**Comment by IAmJSD** [comment]
It isn't, it is the same size as any PFP.

**Comment by ghost** [comment]
I don't think we should accept it, 
1) There's an annoying watermark in the corner.
2) It is distracting.
3) Too different from everything else, nobody else uses GIFs. Would possibly slow the site down too.

**Review by ByteOfMelon — CHANGES_REQUESTED** [review]
We're not allowing pfp GIFs on the site. It's too distracting.

**Pull request closed without merging**
