### PR TITLE
Added new profile pics, removed old ones, and added new staff to staff list

### PR DESCRIPTION
**Pull request by ByteOfMelon**
Self explanatory

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
I'll need to make some changes to this before merging, but thanks for taking care of it! I'll merge after the needed changes are made.

**Review by t5r7 — CHANGES_REQUESTED** [review]
Make them all 150x150 jpgs

**Comment by ByteOfMelon** [comment]
Fixed @mrdnomaid

**Review by t5r7 — APPROVED** [review]
Looks a'ight to me

**Comment by ByteOfMelon** [comment]
@ffxhand i fix it:tm:

**Pull request merged**
