### PR TITLE
Fix the meta descriptions

### PR DESCRIPTION
**Pull request by t5r7**

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
remove Devon stuff since we're not associated with him anymore

**Comment by t5r7** [comment]
Which devon stuff?

**Comment by ghost** [comment]
keywords

**Comment by ghost** [comment]
I'll approve these changes for now, but make another pr removing those @mrdnomaid

**Review by ghost — APPROVED** [review]

**Pull request merged**
